ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: api-testnet.promenade.art
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - secretName: promenade-server-testnet-tls
      hosts:
        - api-testnet.promenade.art
